# Generated by Django 4.2.7 on 2023-11-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('services', models.CharField(choices=[('Service 1', 'Teeth Extractions'), ('Service 2', 'Teeth Whitening'), ('Service 3', 'Dental Crowns'), ('Service 4', 'Dental Clinings'), ('Service 5', 'Cosmetic Dentistry')], max_length=20)),
                ('doctor_choice', models.CharField(choices=[('Doctor 1', 'Doctor 1'), ('Doctor 2', 'Doctor 2')], max_length=20)),
                ('details', models.TextField()),
            ],
        ),
    ]
