# Generated by Django 4.2.7 on 2023-11-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clear', '0002_remove_appointment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.CharField(choices=[('Service 1', 'Teeth Extractions'), ('Service 2', 'Teeth Whitening'), ('Service 3', 'Dental Crowns'), ('Service 4', 'Dental Cleanings'), ('Service 5', 'Cosmetic Dentistry')], max_length=20),
        ),
    ]
