# Generated by Django 4.2.7 on 2023-11-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clear', '0005_service_remove_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Teeth Extractions', 'Teeth Extractions'), ('Teeth Whitening', 'Teeth Whitening'), ('Dental Crowns', 'Dental Crowns'), ('Dental Cleanings', 'Dental Cleanings'), ('Cosmetic Dentistry', 'Cosmetic Dentistry')], default='Teeth Extractions', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_choice',
            field=models.CharField(choices=[('Doctor 1', 'Doctor 1')], default='Doctor 1', max_length=20),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
