# Generated by Django 4.2.7 on 2023-12-09 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clear', '0007_remove_appointment_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='cosmetic_dentistry',
            new_name='Cosmetics_Dentistry',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='dental_cleanings',
            new_name='Dental_Cleaning',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='dental_crowns',
            new_name='Dental_Crowns',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='teeth_extractions',
            new_name='Teeth_Extractions',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='teeth_whitening',
            new_name='Teeth_Whitening',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_choice',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='approval_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(choices=[('Arvilyn', 'Arvilyn'), ('Angelie', 'Angelie')], default='Angelie', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
