# Generated by Django 4.2.7 on 2023-12-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clear', '0008_rename_cosmetic_dentistry_appointment_cosmetics_dentistry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(choices=[('Arvilyn', 'Arvilyn'), ('Angelie', 'Angelie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
