# Generated by Django 4.2.6 on 2024-01-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clear', '0010_registrationdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationData',
        ),
    ]
